# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: TODO to Issue
        # You may pin to the exact commit or the version.
        # uses: alstr/todo-to-issue-action@0db9bdffa1269c2020353b85f28ea34c6fd5e7c8
        uses: alstr/todo-to-issue-action@v4.1
        with:
          # The path to the repository where the action will be used, e.g. 'alstr/my-repo' (automatically set)
          REPO: ${{ github.repository }}
          # The SHA of the last pushed commit (automatically set)
          BEFORE: ${{ github.event.before }}
          # The SHA of the latest commit (automatically set)
          SHA: ${{ github.sha }}
          # The GitHub access token to allow us to retrieve, create and update issues (automatically set)
          TOKEN: ${{ github.token }}
          # Optional input that specifies whether to attempt to close an issue when a TODO is removed
          CLOSE_ISSUES: true
          # For multiline TODOs, format each line as a new paragraph when creating the issue
          AUTO_P: false

